name: CI 

on:
  push:
    branches:
      - master
      - develop
    tags: 'REL-*'

  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build projects
        run: make
      - name: Build projects for release
        if: >-
          github.event_name == 'push' &&
          startsWith(github.event.ref, 'refs/tags')
        run: BUILD_CONFIG=Release make
      - name: Convert 02drv_triangle elf to hex
        if: >-
          github.event_name == 'push' &&
          startsWith(github.event.ref, 'refs/tags')
        run: >-
          objcopy -O ihex
          02drv_triangle/Output/Debug/Exe/02drv_triangle.elf
          02drv_triangle/Output/Debug/Exe/02drv_triangle.hex
      - name: Release
        uses: ncipollo/release-action@v1
        if: >-
          github.event_name == 'push' &&
          startsWith(github.event.ref, 'refs/tags')
        with:
          generateReleaseNotes: true
          artifacts: "
            02drv_triangle/Output/Debug/Exe/02drv_triangle.elf
            02drv_triangle/Output/Debug/Exe/02drv_triangle.hex"
          token: ${{ secrets.RELEASE_TOKEN }}
